# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

name: test-cd

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  release:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@v2
    secrets: inherit
    with:
      testpypi: true
